name: Build and Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug secrets (temporal)
        run: |
          echo "Registry: ${{ secrets.NEXUS_REGISTRY }}"
          echo "User: ${{ secrets.NEXUS_USERNAME }}"
          echo "Password is set: ${{ secrets.NEXUS_PASSWORD != '' }}"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Nexus Registry
        run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login ${{ secrets.NEXUS_REGISTRY }} -u ${{ secrets.NEXUS_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.NEXUS_REGISTRY }}/testsonarnode:latest .

      - name: Push Image to Nexus
        run: docker push ${{ secrets.NEXUS_REGISTRY }}/testsonarnode:latest

      - name: Copy deploy script to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "./deploy.sh"
          target: "/home/${{ secrets.VPS_USER }}/"

      - name: Run deploy script via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            chmod +x ~/deploy.sh
            ~/deploy.sh